### ISSUE TITLE
[OpenCL] Compile error: casting changes address space of pointer

### ISSUE THREAD

**Issue by eltos** [xsuite/xobjects#69]
I am trying to get xsuite running on an AMD GPU with the OpenCL context using the [simple example](https://xsuite.readthedocs.io/en/latest/singlepart.html#a-simple-example) from the getting started guide. I get the following error:
```
Traceback (most recent call last):
  File "/xsuite/example.py", line 32, in <module>
    tracker = xt.Tracker(_context=context, line=line)
  File "/xsuite/xtrack/xtrack/tracker.py", line 101, in __init__
    self._init_track_no_collective(
  File "/xsuite/xtrack/xtrack/tracker.py", line 351, in _init_track_no_collective
    self._build_kernel(save_source_as, compile=compile)
  File "/xsuite/xtrack/xtrack/tracker.py", line 722, in _build_kernel
    context.add_kernels(
  File "/xsuite/xobjects/xobjects/context_pyopencl.py", line 271, in add_kernels
    prg = cl.Program(self.context, specialized_source).build()
  File "/usr/local/lib/python3.10/dist-packages/pyopencl/__init__.py", line 535, in build
    self._prg, was_cached = self._build_and_catch_errors(
  File "/usr/local/lib/python3.10/dist-packages/pyopencl/__init__.py", line 583, in _build_and_catch_errors
    raise err
pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'gfx906:sramecc+:xnack-' on 'AMD Accelerated Parallel Processing' at 0x564a3eb54d60>:

/tmp/comgr-f5172f/input/CompileSource:244:10: error: casting '__global char *' to type '__private char *' changes address space of pointer
  return (char*)(( __global char*) obj+offset);
         ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/comgr-f5172f/input/CompileSource:4612:10: error: casting '__global char *' to type '__private char *' changes address space of pointer
  return (char*)(( __global char*) obj+offset);
         ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/comgr-f5172f/input/CompileSource:4672:31: error: initializing '__private void *__private' with an expression of type '__global void *' changes address space of pointer
                        void* el = ElementRefData_member_elements(elem_ref_data, elem_idx);
                              ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/comgr-f5172f/input/CompileSource:4687:56: error: casting '__private void *' to type 'DriftData' (aka '__global struct DriftData_s *') changes address space of pointer
                            Drift_track_local_particle((DriftData) el, &lpart);
                                                       ^           ~~
/tmp/comgr-f5172f/input/CompileSource:4693:60: error: casting '__private void *' to type 'MultipoleData' (aka '__global struct MultipoleData_s *') changes address space of pointer
                            Multipole_track_local_particle((MultipoleData) el, &lpart);
                                                           ^               ~~
/tmp/comgr-f5172f/input/CompileSource:4699:67: error: casting '__private void *' to type 'ParticlesMonitorData' (aka '__global struct ParticlesMonitorData_s *') changes address space of pointer
                            ParticlesMonitor_track_local_particle((ParticlesMonitorData) el, &lpart);
                                                                  ^                      ~~
6 errors generated.
Error: Failed to compile source (from CL or HIP source to LLVM IR).

(options: -I /usr/local/lib/python3.10/dist-packages/pyopencl/cl)
(source saved as /tmp/tmp3o3ucscd.cl)
```
[tmp3o3ucscd.cl.txt](https://github.com/xsuite/xobjects/files/9926398/tmp3o3ucscd.cl.txt)

My setup is an Ubuntu 22.04 with AMD OpenCL drivers (amdgpu-install --usecase=opencl), python 3.10 and the latest xsuite modules (git clone and pip install -e with the fix described in #68 applied):
```
numpy               1.21.5
cffi                1.15.1
Cython              0.29.32
xdeps               0.0.10
xfields             0.8.4
xobjects            0.1.26
xpart               0.9.2
xsuite              0.4.0
xtrack              0.21.0
pyopencl            2022.2.4
```

If I select the CPU as device in the opencl context (`<pyopencl.Device 'pthread-12th Gen Intel(R) Core(TM) i5-1235U' on 'Portable Computing Language' at 0x5559ba82e500>`) I get the same error message.

**Comment by aoeftiger** [comment]
I have fixed this issue for AMD architectures via openCL in my local branch: https://github.com/aoeftiger/xobjects with 2 commits:

[#d0da689809048e2b943615f4aaf3f7a36a68ca66](https://github.com/xsuite/xobjects/commit/d0da689809048e2b943615f4aaf3f7a36a68ca66)

and 

[#e201b4dc7d4453a3034bf8141b048f9177ff981d](https://github.com/xsuite/xobjects/commit/e201b4dc7d4453a3034bf8141b048f9177ff981d)

**Comment by eltos** [comment]
Thanks @aoeftiger for the hint with the compiler flag. For me just commenting that out did not do the trick, instead I had to manually set a compiler flag:  

Apparently this has to do with the OpenCL C Version (compiler flag `-cl-std=...`).  
While the AMD drivers come with OpenCL C 2.0 (as output of `clinfo` confirms), the compilation is done against the highest supported 1.X version by default and using OpenCL C 2.0 requires explicit passing of that compiler flag ([source](https://man.opencl.org/clBuildProgram.html)).  
The address space changing cast apparently requires OpenCL C 2.0, but is not allowed with versions 1.1, 1.2 etc. hence causing the compiler error. When using OpenCL C 2.0 the code compiles.

Using OpenCL C 2.0 can be done either by setting the environment variable `PYOPENCL_BUILD_OPTIONS="-cl-std=CL2.0"` or passing that compiler flag to the [`.build()`](https://github.com/xsuite/xobjects/blob/28084428d3a96247d09c1b9d6b2d4573bb694ae7/xobjects/context_pyopencl.py#L267) call (see the [pyopencl docu](https://documen.tician.de/pyopencl/runtime_program.html#pyopencl.Program.build)).

**Comment by eltos** [comment]
Maybe one could make the cast compatible with OpenCL C 1.2, or adding a note to the documentation that OpenCL C 2.0 is required and how to set this compiler flag.
