### ISSUE TITLE
[OpenCL] RuntimeError MEM_COPY_OVERLAP during initialisation of ParticleMonitor

### ISSUE THREAD

**Issue by eltos** [xsuite/xobjects#70]
During initialisation of a Particle monitor using the pyopencl context the following error occours:
```
Traceback (most recent call last):
  File "/xsuite/./monitor_test.py", line 22, in <module>
    monitor = xt.ParticlesMonitor(_context=context,
  File "/xsuite/xtrack/xtrack/monitors.py", line 60, in _monitor_init
    self.xoinitialize(
  File "/xsuite/xobjects/xobjects/hybrid_class.py", line 276, in xoinitialize
    self._reinit_from_xobject(_xobject=self._xobject)
  File "/xsuite/xobjects/xobjects/hybrid_class.py", line 243, in _reinit_from_xobject
    setattr(self, pyname, vv)
  File "/xsuite/xobjects/xobjects/hybrid_class.py", line 48, in __set__
    setattr(container._xobject, self.name, value._xobject)
  File "/xsuite/xobjects/xobjects/struct.py", line 104, in __set__
    self.__get__(instance)._update(value)
  File "/xsuite/xobjects/xobjects/struct.py", line 335, in _update
    self._buffer.update_from_xbuffer(
  File "/xsuite/xobjects/xobjects/context.py", line 341, in update_from_xbuffer
    self.update_from_native(
  File "/xsuite/xobjects/xobjects/context_pyopencl.py", line 417, in update_from_native
    cl.enqueue_copy(
  File "/usr/local/lib/python3.10/dist-packages/pyopencl/__init__.py", line 1903, in enqueue_copy
    return _cl._enqueue_copy_buffer(queue, src, dest, **kwargs)
pyopencl._cl.RuntimeError: clEnqueueCopyBuffer failed: MEM_COPY_OVERLAP
```

Minimum code to reproduce:
```python
#!/usr/bin/env python3

import xobjects as xo
import xtrack as xt

xo.ContextPyopencl.print_devices()
context = xo.ContextPyopencl("0.0")  # For OpenCL GPUs

monitor = xt.ParticlesMonitor(_context=context,
                              start_at_turn=5, stop_at_turn=15,
                              num_particles=100)
```
My setup is an Ubuntu 22.04 with AMD OpenCL drivers (amdgpu-install --usecase=opencl), python 3.10 and the latest xsuite modules (git clone and pip install -e with the fix described in https://github.com/xsuite/xobjects/pull/68 applied and the compiler flag described in #69 set)

**Comment by eltos** [comment]
While debuggin I noticed, that the source and destination address space of the copy operation in [`update_from_native`](https://github.com/xsuite/xobjects/blob/28084428d3a96247d09c1b9d6b2d4573bb694ae7/xobjects/context_pyopencl.py#L406-L417) are identical, which I believe is due to the `_reinit_from_xobject` mechanism.  

A simple workaround is a slight modification of the [`update_from_native`](https://github.com/xsuite/xobjects/blob/28084428d3a96247d09c1b9d6b2d4573bb694ae7/xobjects/context_pyopencl.py#L406-L417) method:
```python
def update_from_native(
        self, offset: int, source: cl.Buffer, source_offset: int, nbytes: int
    ):
        """Copy data from native buffer into self.buffer starting from offset"""
        if source == self.buffer and source_offset == offset:
            # copying into the identical address space is redundant and will cause runtime error
            # might happen during object initialisation, see https://github.com/xsuite/xobjects/issues/70
            return
        cl.enqueue_copy(
            self.context.queue,
            self.buffer,
            source,
            src_offset=source_offset,
            dest_offset=offset,#dst_offset=offset,
            byte_count=nbytes,
        )
```

**Comment by rdemaria** [comment]
I would intercept the issue at the calling, rather than adding an `if` in a low-level function or add another function called "check_or_update_from_native"

**Comment by eltos** [comment]
> I would intercept the issue at the calling, rather than adding an `if` in a low-level function or add another function called "check_or_update_from_native"

Absolutely agree so solve it at the root cause, copying buffers onto themselves does not seam right in the first place. That `if` is just a quick workaround to get going, since I don't know where the root cause actually is.
